// Re-export Lucide icons for consistent usage across the app
export {
  MapPin as LocationIcon,
  Clock as ClockIcon,
  Ticket as TicketIcon,
  BookOpen as BookIcon,
  Users as GroupIcon,
  Heart as HeartIcon,
  Send as SendIcon,
  ExternalLink as LinkIcon,
  X as CloseIcon,
  Expand as ExpandIcon,
  FileText as DocumentIcon,
  Calendar as CalendarIcon,
  Building2 as MuseumIcon,
  MapPinned as SourceIcon,
  Sparkles as AIIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  Info as InfoIcon,
  Image as ImageIcon,
  Video as VideoIcon,
} from 'lucide-react';
