import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as lambda from "aws-cdk-lib/aws-lambda";
import * as s3 from "aws-cdk-lib/aws-s3";
import * as s3deploy from "aws-cdk-lib/aws-s3-deployment";
import * as iam from "aws-cdk-lib/aws-iam";
import * as bedrock from "aws-cdk-lib/aws-bedrock";
import * as os from "os";
import {
  opensearchserverless,
  opensearch_vectorindex,
  bedrock as bedrockL2,
} from "@cdklabs/generative-ai-cdk-constructs";

export class MuseumChatbot extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const aws_region = cdk.Stack.of(this).region;
    const aws_account = cdk.Stack.of(this).account;
    console.log(`AWS Region: ${aws_region}`);

    const hostArchitecture = os.arch();
    console.log(`Host architecture: ${hostArchitecture}`);

    const lambdaArchitecture =
      hostArchitecture === "arm64"
        ? lambda.Architecture.ARM_64
        : lambda.Architecture.X86_64;
    console.log(`Lambda architecture: ${lambdaArchitecture}`);

    // ========================================
    // S3 Data Source Bucket
    // ========================================

    // Data source bucket - stores museum documents (PDFs, images, text files)
    const museumDataBucket = new s3.Bucket(this, "MuseumDataBucket", {
      enforceSSL: true,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      versioned: true,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
    });

    // Create placeholder files to establish folder structure for museum data
    const prefixes = ['public/', 'private/'];

    prefixes.forEach(prefix => {
      new s3deploy.BucketDeployment(this, `Deploy${prefix.replace('/', '')}`, {
        sources: [s3deploy.Source.data('.placeholder', ' ')],
        destinationBucket: museumDataBucket,
        destinationKeyPrefix: prefix,
      });
    });

    // Deploy scraped CMC photographs with metadata to the public folder
    // These images have companion .metadata.json files for Bedrock KB filtering
    new s3deploy.BucketDeployment(this, "DeployCMCPhotographs", {
      sources: [s3deploy.Source.asset("./lambda/webcrawler/scraped_data/bedrock_kb_ready/images")],
      destinationBucket: museumDataBucket,
      destinationKeyPrefix: "public/cmc-photographs/",
      prune: false, // Don't delete existing files
    });

    // ========================================
    // Supplemental Data Storage (for multimodal embeddings)
    // ========================================

    // Bucket for storing extracted images from multimodal documents
    // Required when using multimodal embedding models like Nova
    const supplementalDataBucket = new s3.Bucket(this, "SupplementalDataBucket", {
      enforceSSL: true,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
    });

    // ========================================
    // OpenSearch Serverless Vector Collection (L2 Construct)
    // ========================================

    // Create OpenSearch Serverless Vector Collection using cdklabs L2 construct
    // This automatically creates encryption, network, and data access policies
    // Collection name will be auto-generated by CloudFormation
    const vectorCollection = new opensearchserverless.VectorCollection(this, "MuseumVectorCollection", {
      description: "Vector collection for Museum Knowledge Base",
      standbyReplicas: opensearchserverless.VectorCollectionStandbyReplicas.DISABLED, // Cost optimization for dev
    });

    // Create Vector Index within the OpenSearch Serverless collection
    const vectorIndex = new opensearch_vectorindex.VectorIndex(this, "MuseumVectorIndex", {
      collection: vectorCollection,
      indexName: cdk.Names.uniqueResourceName(this, { maxLength: 63, separator: "-" }).toLowerCase(),
      vectorDimensions: 3072, // Amazon Nova Multimodal Embeddings 1.0 dimension
      vectorField: "bedrock-knowledge-base-default-vector",
      precision: "float",
      distanceType: "l2",
      mappings: [
        {
          mappingField: "AMAZON_BEDROCK_TEXT_CHUNK",
          dataType: "text",
          filterable: true,
        },
        {
          mappingField: "AMAZON_BEDROCK_METADATA",
          dataType: "text",
          filterable: false,
        },
      ],
    });

    // ========================================
    // IAM Role for Knowledge Base
    // ========================================

    const knowledgeBaseRole = new iam.Role(this, "KnowledgeBaseRole", {
      assumedBy: new iam.ServicePrincipal("bedrock.amazonaws.com"),
      description: "IAM role for Museum Knowledge Base",
    });

    // Grant full Bedrock access for Knowledge Base operations
    knowledgeBaseRole.addToPolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ["bedrock:*"],
        resources: ["*"],
      })
    );

    // Grant permissions to access the data source bucket
    museumDataBucket.grantRead(knowledgeBaseRole);

    // Grant permissions to access the supplemental data bucket (for multimodal content)
    supplementalDataBucket.grantReadWrite(knowledgeBaseRole);

    // Grant data access to the OpenSearch Serverless collection
    vectorCollection.grantDataAccess(knowledgeBaseRole);

    // Add OpenSearch Serverless API permissions for Knowledge Base
    knowledgeBaseRole.addToPolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ["aoss:APIAccessAll"],
        resources: [vectorCollection.collectionArn],
      })
    );

    // ========================================
    // Knowledge Base with OpenSearch Serverless
    // ========================================

    // Amazon Nova Multimodal Embeddings 1.0 model ARN
    const embeddingModelArn = `arn:aws:bedrock:${aws_region}::foundation-model/amazon.nova-2-multimodal-embeddings-v1:0`;

    // Create the Knowledge Base with OpenSearch Serverless vector store
    const knowledgeBase = new bedrock.CfnKnowledgeBase(this, "MuseumKnowledgeBase", {
      name: `MuseumKnowledgeBase-${cdk.Names.uniqueId(this).slice(-8)}`,
      description: "Knowledge base for Museum containing exhibit information, artwork details, and visitor guides",
      roleArn: knowledgeBaseRole.roleArn,
      knowledgeBaseConfiguration: {
        type: "VECTOR",
        vectorKnowledgeBaseConfiguration: {
          embeddingModelArn: embeddingModelArn,
          embeddingModelConfiguration: {
            bedrockEmbeddingModelConfiguration: {
              dimensions: 3072, // Amazon Nova Multimodal Embeddings 1.0 dimension
              embeddingDataType: "FLOAT32",
            },
          },
          // Supplemental data storage for multimodal content (images extracted from documents)
          supplementalDataStorageConfiguration: {
            supplementalDataStorageLocations: [
              {
                supplementalDataStorageLocationType: "S3",
                s3Location: {
                  uri: `s3://${supplementalDataBucket.bucketName}/`,
                },
              },
            ],
          },
        },
      },
      storageConfiguration: {
        type: "OPENSEARCH_SERVERLESS",
        opensearchServerlessConfiguration: {
          collectionArn: vectorCollection.collectionArn,
          vectorIndexName: vectorIndex.indexName,
          fieldMapping: {
            vectorField: vectorIndex.vectorField,
            textField: "AMAZON_BEDROCK_TEXT_CHUNK",
            metadataField: "AMAZON_BEDROCK_METADATA",
          },
        },
      },
    });

    // Ensure knowledge base is created after vector index and IAM policies are ready
    knowledgeBase.node.addDependency(vectorIndex);
    
    // Add explicit dependency on the IAM role's default policy to ensure permissions
    // are fully propagated before Knowledge Base creation attempts to validate them
    const defaultPolicyConstruct = knowledgeBaseRole.node.tryFindChild('DefaultPolicy');
    if (defaultPolicyConstruct) {
      const cfnPolicy = defaultPolicyConstruct.node.defaultChild as cdk.CfnResource;
      if (cfnPolicy) {
        knowledgeBase.addDependency(cfnPolicy);
      }
    }

    // ========================================
    // Data Source for Knowledge Base (S3)
    // ========================================

    const dataSource = new bedrock.CfnDataSource(this, "MuseumDataSource", {
      name: `MuseumDocuments-${Date.now()}`,
      description: "Museum documents including exhibit guides, artwork information, and visitor resources",
      knowledgeBaseId: knowledgeBase.attrKnowledgeBaseId,
      dataSourceConfiguration: {
        type: "S3",
        s3Configuration: {
          bucketArn: museumDataBucket.bucketArn,
        },
      },
      vectorIngestionConfiguration: {
        // Fixed size chunking (default: 300 tokens, 20% overlap)
        chunkingConfiguration: {
          chunkingStrategy: "FIXED_SIZE",
          fixedSizeChunkingConfiguration: {
            maxTokens: 300,
            overlapPercentage: 20,
          },
        },
        // Use Bedrock Data Automation (BDA) for advanced document parsing
        parsingConfiguration: {
          parsingStrategy: "BEDROCK_DATA_AUTOMATION",
          bedrockDataAutomationConfiguration: {
            parsingModality: "MULTIMODAL",
          },
        },
      },
    });

    // Ensure data source is created after knowledge base
    dataSource.addDependency(knowledgeBase);

    // ========================================
    // Web Crawler Data Source for Museum Websites
    // ========================================
    // - Main website: cincymuseum.org
    // - Collections: searchcollections.cincymuseum.org
    // - Philanthropy: supportcmc.org
    const webCrawlerDataSource = new bedrock.CfnDataSource(this, "MuseumWebCrawlerDataSource", {
      name: `MuseumWebsites-${Date.now()}`,
      description: "Web crawler for Museum websites including main site, collections, and philanthropy",
      knowledgeBaseId: knowledgeBase.attrKnowledgeBaseId,
      dataSourceConfiguration: {
        type: "WEB",
        webConfiguration: {
          sourceConfiguration: {
            urlConfiguration: {
              seedUrls: [
                { url: "https://www.cincymuseum.org/#gsc.tab=0" },
                // { url: "https://searchcollections.cincymuseum.org" },
                { url: "https://supportcmc.org/" },
              ],
            },
          },
          crawlerConfiguration: {
            crawlerLimits: {
              maxPages: 1500, // Limit pages per seed URL to control costs
              rateLimit: 50, // Requests per minute to be respectful to servers
            },

          },
        },
      },
      vectorIngestionConfiguration: {
        chunkingConfiguration: {
          chunkingStrategy: "FIXED_SIZE",
          fixedSizeChunkingConfiguration: {
            maxTokens: 500,
            overlapPercentage: 20,
          },
        },
        // Use Bedrock Data Automation (BDA) for advanced document parsing
        parsingConfiguration: {
          parsingStrategy: "BEDROCK_DATA_AUTOMATION",
          bedrockDataAutomationConfiguration: {
            parsingModality: "MULTIMODAL",
          },
        },
      },
    });

    // Ensure web crawler data source is created after knowledge base
    webCrawlerDataSource.addDependency(knowledgeBase);

    // ========================================
    // Outputs
    // ========================================

    new cdk.CfnOutput(this, "MuseumDataBucketName", {
      value: museumDataBucket.bucketName,
      description: "S3 bucket for museum documents (upload your PDFs, images, and text files here)",
    });

    new cdk.CfnOutput(this, "SupplementalDataBucketName", {
      value: supplementalDataBucket.bucketName,
      description: "S3 bucket for supplemental data (multimodal extracted images)",
    });

    new cdk.CfnOutput(this, "OpenSearchCollectionArn", {
      value: vectorCollection.collectionArn,
      description: "OpenSearch Serverless Collection ARN for vector storage",
    });

    new cdk.CfnOutput(this, "OpenSearchCollectionEndpoint", {
      value: vectorCollection.collectionEndpoint,
      description: "OpenSearch Serverless Collection Endpoint",
    });

    new cdk.CfnOutput(this, "KnowledgeBaseId", {
      value: knowledgeBase.attrKnowledgeBaseId,
      description: "Bedrock Knowledge Base ID",
    });

    new cdk.CfnOutput(this, "KnowledgeBaseArn", {
      value: knowledgeBase.attrKnowledgeBaseArn,
      description: "Bedrock Knowledge Base ARN",
    });

    new cdk.CfnOutput(this, "DataSourceId", {
      value: dataSource.attrDataSourceId,
      description: "Data Source ID for S3 documents",
    });

    new cdk.CfnOutput(this, "WebCrawlerDataSourceId", {
      value: webCrawlerDataSource.attrDataSourceId,
      description: "Data Source ID for web crawler (Museum websites)",
    });
  }
}