import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as lambda from "aws-cdk-lib/aws-lambda";
import * as s3 from "aws-cdk-lib/aws-s3";
import * as s3deploy from "aws-cdk-lib/aws-s3-deployment";
import * as iam from "aws-cdk-lib/aws-iam";
import * as bedrock from "aws-cdk-lib/aws-bedrock";
import * as apigateway from "aws-cdk-lib/aws-apigateway";
import * as logs from "aws-cdk-lib/aws-logs";
import * as dynamodb from "aws-cdk-lib/aws-dynamodb";
import * as os from "os";
import {
  opensearchserverless,
  opensearch_vectorindex,
  bedrock as bedrockL2,
} from "@cdklabs/generative-ai-cdk-constructs";

export class MuseumChatbot extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const aws_region = cdk.Stack.of(this).region;
    const aws_account = cdk.Stack.of(this).account;
    console.log(`AWS Region: ${aws_region}`);

    const hostArchitecture = os.arch();
    console.log(`Host architecture: ${hostArchitecture}`);

    const lambdaArchitecture =
      hostArchitecture === "arm64"
        ? lambda.Architecture.ARM_64
        : lambda.Architecture.X86_64;
    console.log(`Lambda architecture: ${lambdaArchitecture}`);

    // ========================================
    // S3 Data Source Bucket
    // ========================================

    // Data source bucket - stores museum documents (PDFs, images, text files)
    const museumDataBucket = new s3.Bucket(this, "MuseumDataBucket", {
      enforceSSL: true,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      versioned: true,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
    });

    // Create placeholder files to establish folder structure for museum data
    const prefixes = ['public/', 'private/'];

    prefixes.forEach(prefix => {
      new s3deploy.BucketDeployment(this, `Deploy${prefix.replace('/', '')}`, {
        sources: [s3deploy.Source.data('.placeholder', ' ')],
        destinationBucket: museumDataBucket,
        destinationKeyPrefix: prefix,
      });
    });

    // CMC photographs are uploaded separately via AWS CLI to avoid redeployment on every cdk deploy:
    // aws s3 sync ./lambda/webcrawler/scraped_data/bedrock_kb_ready/images s3://<bucket-name>/public/cmc-photographs/

    // ========================================
    // Supplemental Data Storage (for multimodal embeddings)
    // ========================================

    // Bucket for storing extracted images from multimodal documents
    // Required when using multimodal embedding models like Nova
    const supplementalDataBucket = new s3.Bucket(this, "SupplementalDataBucket", {
      enforceSSL: true,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
    });

    // ========================================
    // DynamoDB Table: User Information
    // ========================================

    // Table to collect and store user information from chatbot interactions
    const userTable = new dynamodb.Table(this, "UserTable", {
      tableName: `MuseumChatbot-Users-${Date.now()}`,
      partitionKey: {
        name: "userId",
        type: dynamodb.AttributeType.STRING,
      },
      sortKey: {
        name: "createdAt",
        type: dynamodb.AttributeType.STRING,
      },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST, // On-demand pricing for cost efficiency
      removalPolicy: cdk.RemovalPolicy.RETAIN, // Retain user data on stack deletion
      pointInTimeRecoverySpecification: {
        pointInTimeRecoveryEnabled: true, // Enable point-in-time recovery for data protection
      },
      encryption: dynamodb.TableEncryption.AWS_MANAGED, // Server-side encryption
    });

    // ========================================
    // OpenSearch Serverless Vector Collection (L2 Construct)
    // ========================================

    // Create OpenSearch Serverless Vector Collection using cdklabs L2 construct
    // This automatically creates encryption, network, and data access policies
    // Collection name will be auto-generated by CloudFormation
    const vectorCollection = new opensearchserverless.VectorCollection(this, "MuseumVectorCollection", {
      description: "Vector collection for Museum Knowledge Base",
      standbyReplicas: opensearchserverless.VectorCollectionStandbyReplicas.DISABLED, // Cost optimization for dev
    });

    // Create Vector Index within the OpenSearch Serverless collection
    const vectorIndex = new opensearch_vectorindex.VectorIndex(this, "MuseumVectorIndex", {
      collection: vectorCollection,
      indexName: cdk.Names.uniqueResourceName(this, { maxLength: 63, separator: "-" }).toLowerCase(),
      vectorDimensions: 3072, // Amazon Nova Multimodal Embeddings 1.0 dimension
      vectorField: "bedrock-knowledge-base-default-vector",
      precision: "float",
      distanceType: "l2",
      mappings: [
        {
          mappingField: "AMAZON_BEDROCK_TEXT_CHUNK",
          dataType: "text",
          filterable: true,
        },
        {
          mappingField: "AMAZON_BEDROCK_METADATA",
          dataType: "text",
          filterable: false,
        },
      ],
    });

    // ========================================
    // IAM Role for Knowledge Base
    // ========================================

    const knowledgeBaseRole = new iam.Role(this, "KnowledgeBaseRole", {
      assumedBy: new iam.ServicePrincipal("bedrock.amazonaws.com"),
      description: "IAM role for Museum Knowledge Base",
    });

    // Grant full Bedrock access for Knowledge Base operations
    knowledgeBaseRole.addToPolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ["bedrock:*"],
        resources: ["*"],
      })
    );

    // Grant permissions to access the data source bucket
    museumDataBucket.grantRead(knowledgeBaseRole);

    // Grant permissions to access the supplemental data bucket (for multimodal content)
    supplementalDataBucket.grantReadWrite(knowledgeBaseRole);

    // Grant data access to the OpenSearch Serverless collection
    vectorCollection.grantDataAccess(knowledgeBaseRole);

    // Add OpenSearch Serverless API permissions for Knowledge Base
    knowledgeBaseRole.addToPolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ["aoss:APIAccessAll"],
        resources: [vectorCollection.collectionArn],
      })
    );

    // ========================================
    // Knowledge Base with OpenSearch Serverless
    // ========================================

    // Amazon Nova Multimodal Embeddings 1.0 model ARN
    const embeddingModelArn = `arn:aws:bedrock:${aws_region}::foundation-model/amazon.nova-2-multimodal-embeddings-v1:0`;

    // Create the Knowledge Base with OpenSearch Serverless vector store
    const knowledgeBase = new bedrock.CfnKnowledgeBase(this, "MuseumKnowledgeBase", {
      name: `MuseumKnowledgeBase-${cdk.Names.uniqueId(this).slice(-8)}`,
      description: "Knowledge base for Museum containing exhibit information, artwork details, and visitor guides",
      roleArn: knowledgeBaseRole.roleArn,
      knowledgeBaseConfiguration: {
        type: "VECTOR",
        vectorKnowledgeBaseConfiguration: {
          embeddingModelArn: embeddingModelArn,
          embeddingModelConfiguration: {
            bedrockEmbeddingModelConfiguration: {
              dimensions: 3072, // Amazon Nova Multimodal Embeddings 1.0 dimension
              embeddingDataType: "FLOAT32",
            },
          },
          // Supplemental data storage for multimodal content (images extracted from documents)
          supplementalDataStorageConfiguration: {
            supplementalDataStorageLocations: [
              {
                supplementalDataStorageLocationType: "S3",
                s3Location: {
                  uri: `s3://${supplementalDataBucket.bucketName}/`,
                },
              },
            ],
          },
        },
      },
      storageConfiguration: {
        type: "OPENSEARCH_SERVERLESS",
        opensearchServerlessConfiguration: {
          collectionArn: vectorCollection.collectionArn,
          vectorIndexName: vectorIndex.indexName,
          fieldMapping: {
            vectorField: vectorIndex.vectorField,
            textField: "AMAZON_BEDROCK_TEXT_CHUNK",
            metadataField: "AMAZON_BEDROCK_METADATA",
          },
        },
      },
    });

    // Ensure knowledge base is created after vector index and IAM policies are ready
    knowledgeBase.node.addDependency(vectorIndex);
    
    // Add explicit dependency on the IAM role's default policy to ensure permissions
    // are fully propagated before Knowledge Base creation attempts to validate them
    const defaultPolicyConstruct = knowledgeBaseRole.node.tryFindChild('DefaultPolicy');
    if (defaultPolicyConstruct) {
      const cfnPolicy = defaultPolicyConstruct.node.defaultChild as cdk.CfnResource;
      if (cfnPolicy) {
        knowledgeBase.addDependency(cfnPolicy);
      }
    }

    // ========================================
    // Data Source for Knowledge Base (S3)
    // ========================================

    const dataSource = new bedrock.CfnDataSource(this, "MuseumDataSource", {
      name: "MuseumDocuments-v2",
      description: "Museum documents including exhibit guides, artwork information, and visitor resources",
      knowledgeBaseId: knowledgeBase.attrKnowledgeBaseId,
      dataSourceConfiguration: {
        type: "S3",
        s3Configuration: {
          bucketArn: museumDataBucket.bucketArn,
        },
      },
      vectorIngestionConfiguration: {
        // Fixed size chunking (default: 300 tokens, 20% overlap)
        chunkingConfiguration: {
          chunkingStrategy: "FIXED_SIZE",
          fixedSizeChunkingConfiguration: {
            maxTokens: 300,
            overlapPercentage: 20,
          },
        },
        // Use Bedrock Data Automation (BDA) for advanced document parsing
        parsingConfiguration: {
          parsingStrategy: "BEDROCK_DATA_AUTOMATION",
          bedrockDataAutomationConfiguration: {
            parsingModality: "MULTIMODAL",
          },
        },
      },
    });

    // Ensure data source is created after knowledge base
    dataSource.addDependency(knowledgeBase);

    // ========================================
    // Web Crawler Data Source for Museum Websites
    // ========================================
    // - Main website: cincymuseum.org
    // - Collections: searchcollections.cincymuseum.org
    // - Philanthropy: supportcmc.org
    const webCrawlerDataSource = new bedrock.CfnDataSource(this, "MuseumWebCrawlerDataSource", {
      name: "MuseumWebsites-v2",
      description: "Web crawler for Museum websites including main site, collections, and philanthropy",
      knowledgeBaseId: knowledgeBase.attrKnowledgeBaseId,
      dataSourceConfiguration: {
        type: "WEB",
        webConfiguration: {
          sourceConfiguration: {
            urlConfiguration: {
              seedUrls: [
                { url: "https://www.cincymuseum.org/#gsc.tab=0" },
                // { url: "https://searchcollections.cincymuseum.org" },
                { url: "https://supportcmc.org/" },
              ],
            },
          },
          crawlerConfiguration: {
            crawlerLimits: {
              maxPages: 1500, // Limit pages per seed URL to control costs
              rateLimit: 50, // Requests per minute to be respectful to servers
            },

          },
        },
      },
      vectorIngestionConfiguration: {
        chunkingConfiguration: {
          chunkingStrategy: "FIXED_SIZE",
          fixedSizeChunkingConfiguration: {
            maxTokens: 500,
            overlapPercentage: 20,
          },
        },
        // Use Bedrock Data Automation (BDA) for advanced document parsing
        parsingConfiguration: {
          parsingStrategy: "BEDROCK_DATA_AUTOMATION",
          bedrockDataAutomationConfiguration: {
            parsingModality: "MULTIMODAL",
          },
        },
      },
    });

    // Ensure web crawler data source is created after knowledge base
    webCrawlerDataSource.addDependency(knowledgeBase);

    // ========================================
    // Lambda Function: Invoke Knowledge Base
    // ========================================

    // Create IAM role for the Lambda function
    const invokeKbLambdaRole = new iam.Role(this, "InvokeKbLambdaRole", {
      assumedBy: new iam.ServicePrincipal("lambda.amazonaws.com"),
      description: "IAM role for Knowledge Base invocation Lambda",
      managedPolicies: [
        iam.ManagedPolicy.fromManagedPolicyArn(
          this,
          "LambdaBasicExecution",
          "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        ),
      ],
    });

    // Grant permissions to invoke Bedrock Knowledge Base
    invokeKbLambdaRole.addToPolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: [
          "bedrock:RetrieveAndGenerate",
          "bedrock:Retrieve",
          "bedrock:InvokeModel",
          "bedrock:InvokeModelWithResponseStream",
          "bedrock:GetInferenceProfile",
        ],
        resources: ["*"],
      })
    );

    // Lambda function to invoke Knowledge Base with Retrieve and Generate API
    const invokeKbLambda = new lambda.Function(this, "InvokeKbLambda", {
      runtime: lambda.Runtime.PYTHON_3_13,
      architecture: lambdaArchitecture,
      handler: "index.handler",
      code: lambda.Code.fromAsset("lambda/invoke-kb"),
      role: invokeKbLambdaRole,
      timeout: cdk.Duration.minutes(5),
      memorySize: 512,
      environment: {
        KNOWLEDGE_BASE_ID: knowledgeBase.attrKnowledgeBaseId,
      },
      description: "Invokes Bedrock Knowledge Base with Retrieve and Generate API for multimodal responses",
    });

    // Ensure Lambda is created after Knowledge Base
    invokeKbLambda.node.addDependency(knowledgeBase);

    // ========================================
    // Streaming Lambda Function with Lambda Web Adapter
    // ========================================
    // Uses Lambda Web Adapter Layer for Python response streaming
    // Reference: https://github.com/aws-samples/serverless-samples/tree/main/apigw-response-streaming/python-strands-lambda

    // Lambda Web Adapter Layer ARN (managed by AWS)
    // See: https://github.com/awslabs/aws-lambda-web-adapter
    const lambdaWebAdapterLayerArn = lambdaArchitecture === lambda.Architecture.ARM_64
      ? `arn:aws:lambda:${aws_region}:753240598075:layer:LambdaAdapterLayerArm64:25`
      : `arn:aws:lambda:${aws_region}:753240598075:layer:LambdaAdapterLayerX86:25`;

    // Streaming Lambda function with FastAPI and Lambda Web Adapter
    const invokeKbStreamLambda = new lambda.Function(this, "InvokeKbStreamLambda", {
      runtime: lambda.Runtime.PYTHON_3_13,
      architecture: lambdaArchitecture,
      handler: "run.sh",
      code: lambda.Code.fromAsset("lambda/invoke-kb-stream", {
        bundling: {
          image: lambda.Runtime.PYTHON_3_13.bundlingImage,
          command: [
            "bash", "-c",
            "pip install -r requirements.txt -t /asset-output && cp -au . /asset-output"
          ],
        },
      }),
      timeout: cdk.Duration.minutes(5),
      memorySize: 512,
      environment: {
        KNOWLEDGE_BASE_ID: knowledgeBase.attrKnowledgeBaseId,
        AWS_LAMBDA_EXEC_WRAPPER: "/opt/bootstrap",
        AWS_LWA_INVOKE_MODE: "response_stream",
        PORT: "8000",
      },
      layers: [
        lambda.LayerVersion.fromLayerVersionArn(this, "LambdaWebAdapterLayer", lambdaWebAdapterLayerArn),
      ],
      description: "Streaming Lambda with FastAPI for Bedrock KB (uses Lambda Web Adapter)",
    });

    // Grant permissions to invoke Bedrock Knowledge Base
    invokeKbStreamLambda.addToRolePolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: [
          "bedrock:RetrieveAndGenerate",
          "bedrock:Retrieve",
          "bedrock:InvokeModel",
          "bedrock:InvokeModelWithResponseStream",
          "bedrock:GetInferenceProfile",
        ],
        resources: ["*"],
      })
    );

    // Ensure Lambda is created after Knowledge Base
    invokeKbStreamLambda.node.addDependency(knowledgeBase);

    // ========================================
    // REST API Gateway with Response Streaming
    // ========================================

    // IAM Role for API Gateway to write to CloudWatch Logs
    const apiGatewayCloudWatchRole = new iam.Role(this, "ApiGatewayCloudWatchRole", {
      assumedBy: new iam.ServicePrincipal("apigateway.amazonaws.com"),
      managedPolicies: [
        iam.ManagedPolicy.fromManagedPolicyArn(
          this,
          "ApiGatewayPushToCloudWatch",
          "arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"
        ),
      ],
    });

    // API Gateway Account Configuration (required for CloudWatch logging)
    const apiGatewayAccount = new apigateway.CfnAccount(this, "ApiGatewayAccount", {
      cloudWatchRoleArn: apiGatewayCloudWatchRole.roleArn,
    });

    // CloudWatch Log Group for API Gateway Access Logs
    const apiAccessLogs = new logs.LogGroup(this, "ApiGatewayAccessLogs", {
      retention: logs.RetentionDays.ONE_MONTH,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    // REST API with response streaming support
    const api = new apigateway.RestApi(this, "MuseumChatbotApi", {
      restApiName: "Museum Chatbot API",
      description: "REST API for Museum Chatbot with response streaming support",
      deployOptions: {
        stageName: "prod",
        accessLogDestination: new apigateway.LogGroupLogDestination(apiAccessLogs),
        accessLogFormat: apigateway.AccessLogFormat.jsonWithStandardFields(),
      },
      defaultCorsPreflightOptions: {
        allowOrigins: apigateway.Cors.ALL_ORIGINS,
        allowMethods: apigateway.Cors.ALL_METHODS,
        allowHeaders: apigateway.Cors.DEFAULT_HEADERS,
      },
    });

    // Ensure API is created after the account configuration
    api.node.addDependency(apiGatewayAccount);

    // Create /chat resource
    const chatResource = api.root.addResource("chat");

    // Lambda integration with response streaming enabled
    // Uses ResponseTransferMode.STREAM for streaming responses
    const streamingIntegration = new apigateway.LambdaIntegration(invokeKbStreamLambda, {
      proxy: true,
      responseTransferMode: apigateway.ResponseTransferMode.STREAM,
    });

    // POST /chat - Streaming chat endpoint
    chatResource.addMethod("POST", streamingIntegration);

    // ========================================
    // Outputs
    // ========================================

    new cdk.CfnOutput(this, "MuseumDataBucketName", {
      value: museumDataBucket.bucketName,
      description: "S3 bucket for museum documents (upload your PDFs, images, and text files here)",
    });

    new cdk.CfnOutput(this, "SupplementalDataBucketName", {
      value: supplementalDataBucket.bucketName,
      description: "S3 bucket for supplemental data (multimodal extracted images)",
    });

    new cdk.CfnOutput(this, "OpenSearchCollectionArn", {
      value: vectorCollection.collectionArn,
      description: "OpenSearch Serverless Collection ARN for vector storage",
    });

    new cdk.CfnOutput(this, "OpenSearchCollectionEndpoint", {
      value: vectorCollection.collectionEndpoint,
      description: "OpenSearch Serverless Collection Endpoint",
    });

    new cdk.CfnOutput(this, "KnowledgeBaseId", {
      value: knowledgeBase.attrKnowledgeBaseId,
      description: "Bedrock Knowledge Base ID",
    });

    new cdk.CfnOutput(this, "KnowledgeBaseArn", {
      value: knowledgeBase.attrKnowledgeBaseArn,
      description: "Bedrock Knowledge Base ARN",
    });

    new cdk.CfnOutput(this, "DataSourceId", {
      value: dataSource.attrDataSourceId,
      description: "Data Source ID for S3 documents",
    });

    new cdk.CfnOutput(this, "WebCrawlerDataSourceId", {
      value: webCrawlerDataSource.attrDataSourceId,
      description: "Data Source ID for web crawler (Museum websites)",
    });

    new cdk.CfnOutput(this, "InvokeKbLambdaArn", {
      value: invokeKbLambda.functionArn,
      description: "Lambda function ARN for invoking Knowledge Base",
    });

    new cdk.CfnOutput(this, "InvokeKbLambdaName", {
      value: invokeKbLambda.functionName,
      description: "Lambda function name for invoking Knowledge Base",
    });

    new cdk.CfnOutput(this, "StreamingLambdaArn", {
      value: invokeKbStreamLambda.functionArn,
      description: "Streaming Lambda function ARN",
    });

    new cdk.CfnOutput(this, "ChatApiUrl", {
      value: `${api.url}chat`,
      description: "API Gateway URL for streaming chat endpoint (POST /chat)",
    });

    new cdk.CfnOutput(this, "UserTableName", {
      value: userTable.tableName,
      description: "DynamoDB table for storing user information",
    });

    new cdk.CfnOutput(this, "UserTableArn", {
      value: userTable.tableArn,
      description: "DynamoDB table ARN for user information",
    });
  }
}